// Date: 30.05.2021 22:04:48
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mrfinger.gothicgamemod.client.model;
/*
public class ModelScavenger extends ModelAnimal
{
  //fields
    ModelRenderer corpus;
    ModelRenderer neck0;
    ModelRenderer neck1;
    ModelRenderer head;
    ModelRenderer jaw;
    ModelRenderer hip0Right;
    ModelRenderer hip1Right;
    ModelRenderer shinRight;
    ModelRenderer foot0LateralRight;
    ModelRenderer foot0InnerRight;
    ModelRenderer foot1LateralRight;
    ModelRenderer foot1InnerRight;
  
  public ModelScavenger()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      corpus = new ModelRenderer(this, 0, 0);
      corpus.addBox(-3F, -3.5F, -8F, 6, 6, 10);
      corpus.setRotationPoint(0F, 9.5F, 1F);
      corpus.setTextureSize(64, 32);
      corpus.mirror = true;
      setRotation(corpus, -0.1745329F, 0F, 0F);
      neck0 = new ModelRenderer(this, 0, 16);
      neck0.addBox(-1.5F, -1F, -4.6F, 3, 3, 5);
      neck0.setRotationPoint(0F, 8.8F, -7F);
      neck0.setTextureSize(64, 32);
      neck0.mirror = true;
      setRotation(neck0, 0F, 0F, 0F);
      neck1 = new ModelRenderer(this, 0, 24);
      neck1.addBox(-1.5F, -4F, -1.8F, 3, 5, 3);
      neck1.setRotationPoint(0F, 9.8F, -10F);
      neck1.setTextureSize(64, 32);
      neck1.mirror = true;
      setRotation(neck1, 0.1396263F, 0F, 0F);
      head = new ModelRenderer(this, 16, 16);
      head.addBox(-2F, -4F, -6.5F, 4, 4, 7);
      head.setRotationPoint(0F, 5.8F, -9.5F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0.1396263F, 0F, 0F);
      jaw = new ModelRenderer(this, 12, 27);
      jaw.addBox(-1.5F, 0.4F, -4F, 3, 1, 4);
      jaw.setRotationPoint(0F, 5.6F, -12F);
      jaw.setTextureSize(64, 32);
      jaw.mirror = true;
      setRotation(jaw, 0.1396263F, 0F, 0F);
      hip0Right = new ModelRenderer(this, 32, 0);
      hip0Right.addBox(-2F, -1F, -1.5F, 3, 4, 3);
      hip0Right.setRotationPoint(-3F, 9.5F, 1F);
      hip0Right.setTextureSize(64, 32);
      hip0Right.mirror = true;
      setRotation(hip0Right, 0F, 0F, 0F);
      hip1Right = new ModelRenderer(this, 32, 7);
      hip1Right.addBox(-1F, -1.5F, -0.8F, 2, 2, 5);
      hip1Right.setRotationPoint(-4F, 12F, 0.5F);
      hip1Right.setTextureSize(64, 32);
      hip1Right.mirror = true;
      setRotation(hip1Right, -0.3490659F, 0F, 0F);
      shinRight = new ModelRenderer(this, 32, 14);
      shinRight.addBox(-1F, -0.8F, -0.5F, 2, 7, 2);
      shinRight.setRotationPoint(-4F, 12.5F, 4F);
      shinRight.setTextureSize(64, 32);
      shinRight.mirror = true;
      setRotation(shinRight, -0.4363323F, 0F, 0F);
      foot0LateralRight = new ModelRenderer(this, 46, 0);
      foot0LateralRight.addBox(-1F, 0F, -1F, 2, 7, 2);
      foot0LateralRight.setRotationPoint(-4F, 18F, 2.2F);
      foot0LateralRight.setTextureSize(64, 32);
      foot0LateralRight.mirror = true;
      setRotation(foot0LateralRight, -0.4363323F, 0.7853982F, -0.2617994F);
      foot0InnerRight = new ModelRenderer(this, 54, 0);
      foot0InnerRight.addBox(-1F, 0F, -1F, 2, 7, 2);
      foot0InnerRight.setRotationPoint(-4F, 18F, 2.2F);
      foot0InnerRight.setTextureSize(64, 32);
      foot0InnerRight.mirror = true;
      setRotation(foot0InnerRight, -0.2617994F, 0.7853982F, -0.4363323F);
      foot1LateralRight = new ModelRenderer(this, 46, 9);
      foot1LateralRight.addBox(-1.2F, 0F, -4F, 2, 2, 5);
      foot1LateralRight.setRotationPoint(-4.8F, 22F, 0F);
      foot1LateralRight.setTextureSize(64, 32);
      foot1LateralRight.mirror = true;
      setRotation(foot1LateralRight, 0F, 0.2617994F, 0F);
      foot1InnerRight = new ModelRenderer(this, 46, 16);
      foot1InnerRight.addBox(-0.8F, 0F, -4F, 2, 2, 5);
      foot1InnerRight.setRotationPoint(-3.4F, 22F, 0F);
      foot1InnerRight.setTextureSize(64, 32);
      foot1InnerRight.mirror = true;
      setRotation(foot1InnerRight, 0F, -0.2617994F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    corpus.render(f5);
    neck0.render(f5);
    neck1.render(f5);
    head.render(f5);
    jaw.render(f5);
    hip0Right.render(f5);
    hip1Right.render(f5);
    shinRight.render(f5);
    foot0LateralRight.render(f5);
    foot0InnerRight.render(f5);
    foot1LateralRight.render(f5);
    foot1InnerRight.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
*/